### ISSUE TITLE
/model/metadata returns unexpected results

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Text-Sentiment-Classifier#2]
```
{
  "id": "sentiment_bert_base_uncased_tensorflow",
  "name": "Bert Base Uncased TensorFlow Model",
  "description": "BERT Base finetuned on the IBM Project Debater Claim Sentiment dataset.",
  "type": "Text Classification",
  "source": "https://developer.ibm.com/exchanges/models",
  "license": "ApacheV2"
}
```

Issues:
 - source URL is incorrect (should point to https://developer.ibm.com/exchanges/models/all/max-text-sentiment-classifier/)
 - license name doesn't meet standard
 - id naming convention doesn't meet standard

**Comment by splovyt** [comment]
Fixed in https://github.com/IBM/MAX-Text-Sentiment-Classifier/commit/c76cfa9fe09f5cf28a55645b73efd3057030bc5b

Thanks @ptitzler!
