### ISSUE TITLE
During training setup: Error. "sample_training_data/" does not contain files

### ISSUE THREAD

**Issue by thisisrandy** [IBM/MAX-Text-Sentiment-Classifier#20]
Repro steps, all per training/README.md:

1. Clone the repo
2. `cd training`
3. `pip install -r requirements.txt`
4. `./setup_max_model_training max-text-classifier-training-config.yaml`
5. Follow instructions to step, "Bucket is empty. Enter 'Y' to upload data from local directory or press 'ENTER' if you don't want to upload:"
6. Press `y`, `<enter>` (to use sample_training_data/)
7. '[MESSAGE] Error. "sample_training_data/" does not contain files' appears

```
> cd sample_training_data
> ll
total 88K
-rw-r--r-- 1 randy randy 83K Nov  9 12:19 ibm_claim_stance_dataset_reformatted.tsv
-rw-r--r-- 1 randy randy 797 Nov  9 12:19 README.md
```

This is with python 3.6.8 on Ubuntu 18.04. 

I'm guessing that I can manually upload the data later with the same effect (haven't tried yet), but this is obviously not intended behavior. Additionally, note that it breaks the setup script, which is at this point stuck in a loop prompting for a data directory path but not accepting any paths as valid.

**Comment by ptitzler** [comment]
@thisisrandy We'll publish a fix later today. The easiest workaround is to uninstall version 0.1.1 (`pip uninstall max-training-framework`) and install version 0.1.0 of the `max-training-framework` package (`pip install 'max-training-framework==0.1.0'`.

**Comment by ptitzler** [comment]
The issue should now  be resolved. If you clone this repository again and install the `training/requirements.txt` model training should work as expected. The latest version of the `max-training-framework` package expects data files to reside in a subdirectory named `data`. This model was still using the old directory layout and setup therefore couldn't find the tsv file.

**Comment by thisisrandy** [comment]
Confirmed fixed. Thanks for the quick reply!
