### ISSUE TITLE
Trouble verifying checksum (sha512sum)

### ISSUE THREAD

**Issue by alxstan22** [IBM/MAX-Text-Sentiment-Classifier#42]
Could not verify sha512sums.txt check sum file with 
`shasum -a 512 -c max-text-sentiment-classifier-master/sha512sums.txt` 
and recieved this error:

```
shasum: assets/labels.txt:
assets/labels.txt: FAILED open or read
shasum: assets/saved_model.pb: No such file or directory
assets/saved_model.pb: FAILED open or read
shasum: assets/vocab.txt: No such file or directory
assets/vocab.txt: FAILED open or read
shasum: assets/variables/variables.data-00000-of-00001: No such file or directory
assets/variables/variables.data-00000-of-00001: FAILED open or read
shasum: assets/variables/variables.index: No such file or directory
assets/variables/variables.index: FAILED open or read
shasum: WARNING: 5 listed files could not be read
```

According to [this Github issue](https://github.com/helm/helm/issues/7567) the checksum can’t be validated after download with the current sha512sum.txt format, and each file may need to be split into separate files with their file name followed by the `.sha512sum` extension before distribution? Hopefully this is the fix.

**Comment by xuhdev** [comment]
Did you encounter the error when you were building the Docker image (i.e. `docker build`)? The assets are not shipped with the repo, and they will be downloaded during the Docker image build phase.

**Comment by alxstan22** [comment]
No i did not encounter this during the `docker build`; only when I manually entered the `shasum -a 512 -c` into the terminal after running the build did I get this error. For clarity, does this mean the checksum can only be checked successfully within the build?

**Comment by xuhdev** [comment]
As I pointed out in https://github.com/IBM/MAX-Text-Sentiment-Classifier/issues/41#issuecomment-692282166, the files aren't downloaded directly into your filesystem, but into the Docker image that you've built. That's why shasum fails to read.
